Old CI script

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -13,7 +13,7 @@ jobs:
         python-version: 3.8
     - name: before_install
       run: |
-        sudo apt-get install build-essential git libboost-all-dev cmake libgmp3-dev libssl-dev libsodium-dev libprocps-dev pkg-config gcc-10 g++-10
+        sudo apt-get install build-essential git libboost-all-dev cmake libgmp3-dev libssl-dev libsodium-dev libprocps-dev pkg-config gcc-5 g++-5
         sudo apt-get install clang-tidy
         git submodule init && git submodule update
         mkdir build
@@ -24,15 +24,17 @@ jobs:
       id: clang_tidy
       run: |
         cd build
-        python3 run-clang-tidy.py -quiet 2>&1
+        OUTPUT=$(python3 run-clang-tidy.py -quiet 2>&1)
+        echo "::set-output name=OUTPUT::$OUTPUT"
+        COUNT=$(echo $OUTPUT | grep "warning:" | wc -l)
+        echo "::set-output name=COUNT::$COUNT"
+    - name: check_errors
+      if: steps.clang_tidy.outputs.COUNT > 0
+      run: |
+      echo "Clang-tidy failed. Please look at the run_clang_tidy step to see the details."
+        exit 1
     - name: tests
       run: |
+        cd build
         make
         make check
-    - name: run_debug
-      run: |
-        rm -r build/*
-        cd build
-        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DUSE_CLANG_TIDY=OFF -DDEBUG=ON .. 
-        make
-        make check  
