Reordred CI

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -28,6 +28,11 @@ jobs:
         echo "::set-output name=OUTPUT::$OUTPUT"
         COUNT=$(echo $OUTPUT | grep "warning:" | wc -l)
         echo "::set-output name=COUNT::$COUNT"
+    - name: check_errors
+      if: steps.clang_tidy.outputs.COUNT > 0
+      run: |
+        echo "Clang-tidy failed. Please look at the run_clang_tidy step to see the details."
+        exit 20
     - name: tests
       run: |
         make
@@ -39,8 +44,3 @@ jobs:
         cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DUSE_CLANG_TIDY=OFF -DDEBUG=ON .. 
         make
         make check  
-    - name: check_errors
-      if: steps.clang_tidy.outputs.COUNT > 0
-      run: |
-        echo "Clang-tidy failed. Please look at the run_clang_tidy step to see the details."
-        exit 20
